services:
  db:
    image: mysql:9.3
    container_name: mysql-fulll-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'fulll'
      MYSQL_PASSWORD: 'fulll-backend'
      MYSQL_ROOT_PASSWORD: 'fulll-backend-root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - fulll-db:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin-fulll
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'fulll-backend'
    networks:
      - mysql-phpmyadmin

volumes:
  fulll-db:

networks:
  mysql-phpmyadmin:
    driver: bridge
